import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const processors={};
const sandbox={sampleRate:48000,Float32Array,Math,AudioWorkletProcessor:class{constructor(){this.port={onmessage:null,postMessage(){}};}},registerProcessor:(name,Processor)=>{processors[name]=Processor;}};
vm.runInNewContext(readFileSync('public/audio/tape-processor.js','utf8'),sandbox);
const Tape=processors['magnetic-tape'];
function render(heads,feedback=0,enabled=1,blocks=400){const processor=new Tape();processor.heads=heads;processor.headLevels=[...heads];const p={};for(const param of Tape.parameterDescriptors)p[param.name]=new Float32Array([param.defaultValue]);p.feedback[0]=feedback;p.mix[0]=1;p.enabled[0]=enabled;p.wow[0]=0;p.flutter[0]=0;p.crinkle[0]=0;p.hiss[0]=0;p.drive[0]=.5;const output=new Float32Array(blocks*128);for(let block=0;block<blocks;block++){const input=[new Float32Array(128),new Float32Array(128)],out=[new Float32Array(128),new Float32Array(128)];if(block===0){input[0][0]=.5;input[1][0]=.5;}processor.process([input],[out],p);output.set(out[0],block*128);}return output;}
for(let head=0;head<3;head++){const heads=[0,0,0];heads[head]=1;const out=render(heads);let max=0,index=0;for(let i=0;i<out.length;i++)if(Math.abs(out[i])>max){max=Math.abs(out[i]);index=i;}assert(Math.abs(index-48000*.22*(head+1))<2,`Head ${head+1} delay: ${index}`);assert(max>.05);}
process.stdout.write('PASS Three playback heads arrive at 220 / 440 / 660 ms\n');
const bypass=render([1,1,1],.6,0);assert(Math.abs(bypass[0]-.5)<1e-6);assert(bypass.slice(1).every(x=>x===0));process.stdout.write('PASS Bypass preserves dry signal without echo\n');
const feedback=render([1,1,1],1.08,1,3000);assert(feedback.every(Number.isFinite));assert(feedback.every(x=>Math.abs(x)<1));process.stdout.write('PASS Maximum feedback remains finite and bounded over eight seconds\n');
const Capture=processors['magnetic-capture'];const capture=new Capture();const messages=[];capture.port.postMessage=message=>messages.push(message);capture.port.onmessage({data:'start'});for(let i=0;i<70;i++){const input=[new Float32Array(128).fill(.25),new Float32Array(128).fill(-.1)];capture.process([input],[[new Float32Array(128),new Float32Array(128)]]);}capture.port.onmessage({data:'stop'});assert.equal(messages.filter(m=>m.type==='chunk').reduce((n,m)=>n+m.left.length,0),70*128);assert.equal(messages.at(-1).type,'done');assert.equal(messages.at(-1).frames,70*128);assert(messages.filter(m=>m.type==='chunk').every(m=>m.left.every(v=>v===.25)));process.stdout.write('PASS PCM recorder flushes complete and partial chunks before stop acknowledgement\n');

function parameters(){return Object.fromEntries(Tape.parameterDescriptors.map(p=>[p.name,new Float32Array([p.defaultValue])]));}
function signal(settings={},sendLevel=1,blocks=650){const proc=new Tape(),p=parameters();for(const [key,v] of Object.entries(settings))p[key][0]=v;const rendered=new Float32Array(blocks*128);for(let b=0;b<blocks;b++){const dry=[new Float32Array(128),new Float32Array(128)],send=[new Float32Array(128),new Float32Array(128)],out=[new Float32Array(128),new Float32Array(128)];for(let i=0;i<128;i++){const t=(b*128+i)/48000,v=t<.12?Math.sin(t*Math.PI*440*2)*.4:0;dry[0][i]=dry[1][i]=v;send[0][i]=send[1][i]=v*sendLevel;}proc.process([dry,send],[out],p);rendered.set(out[0],b*128);}return rendered;}
const energy=a=>a.reduce((n,v)=>n+v*v,0);
const noSend=signal({mix:1,hiss:0},0);assert(energy(noSend)<1e-10,'A zero echo send produces no echoes');assert(energy(signal({mix:1,hiss:0},1))>.1);
const clean=signal({mix:0,enabled:0,hiss:0}),worn=signal({mix:0,age:.9,drive:.8,wow:.8,flutter:.8,crinkle:.7,hiss:0});assert(energy(clean.map((v,i)=>v-worn[i]))>1,'Tape character changes the dry source');
console.log('PASS Independent echo input and audible tape colour on the dry bus');
const Space=processors['magnetic-space'];
function room(decay){const room=new Space(),p={decay:new Float32Array([decay]),damping:new Float32Array([.2])};let tail=0;for(let b=0;b<2400;b++){const input=[new Float32Array(128),new Float32Array(128)],out=[new Float32Array(128),new Float32Array(128)];if(b===0)input[0][0]=input[1][0]=.5;room.process([input],[out],p);assert(out.every(c=>c.every(v=>Number.isFinite(v)&&Math.abs(v)<1)));if(b>1900)tail+=energy(out[0])+energy(out[1]);}room.port.onmessage({data:{clear:true}});assert(room.lines.every(c=>c.every(v=>v===0)));return tail;}
assert(room(18)>room(1)*100,'Long ambient decay preserves more late energy than a short room');console.log('PASS Ambient room decay, bounded output and tail clear');
