import {chromium} from 'playwright';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://localhost:4173';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--autoplay-policy=no-user-gesture-required']});
const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true,permissions:['microphone'],reducedMotion:'reduce'});
await context.addInitScript(()=>{window.__sources=[];const source=AudioContext.prototype.createBufferSource;AudioContext.prototype.createBufferSource=function(...args){const node=source.apply(this,args);window.__sources.push(node);return node;};window.__bufferAllocations=0;const original=AudioContext.prototype.createBuffer;AudioContext.prototype.createBuffer=function(...args){window.__bufferAllocations++;return original.apply(this,args);};});
const page=await context.newPage();const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const checks=[];
const pass=name=>{checks.push(name);process.stdout.write(`PASS ${name}\n`);};
function wav(){const sr=24000,frames=sr*3,b=Buffer.alloc(44+frames*2);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(sr,24);b.writeUInt32LE(sr*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(frames*2,40);for(let i=0;i<frames;i++){const t=i/sr;const s=t<.15?Math.sin(t*Math.PI*440*2)*Math.exp(-t*20)*.5:0;b.writeInt16LE(Math.round(s*32767),44+i*2);}return b;}
try{
  await page.goto(base);await page.getByText('Saved on this device',{exact:true}).waitFor();
  assert.equal(await page.getByRole('slider').count(),30);
  assert.equal(await page.getByRole('button',{name:/Select track [1-4]: Empty tape/}).count(),4);
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  pass('Empty desktop studio and 30 accessible controls');
  for(const size of [{width:1440,height:900},{width:1366,height:768},{width:1280,height:800}]){
    await page.setViewportSize(size);
    const cabinet=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollHeight,overflow:document.documentElement.scrollWidth,top:document.querySelector('.instrument').getBoundingClientRect().top,panels:['.mechanical-bay','.control-panel','.tape-recorder','.character-rack','.performance-strip','.cloud-panel','.master-recorder'].map(selector=>{const r=document.querySelector(selector).getBoundingClientRect();return {selector,x:r.x,y:r.y,right:r.right,bottom:r.bottom};})}));
    assert(cabinet.top<=12,'The cabinet starts immediately below the browser edge');assert(cabinet.overflow<=cabinet.width);
    for(let i=0;i<cabinet.panels.length;i++)for(let j=i+1;j<cabinet.panels.length;j++){const a=cabinet.panels[i],b=cabinet.panels[j];assert(a.right<=b.x+.5||b.right<=a.x+.5||a.bottom<=b.y+.5||b.bottom<=a.y+.5,`Control plates do not overlap: ${a.selector} / ${b.selector}`);}
    await page.screenshot({path:`test-results/cabinet-${size.width}.png`,fullPage:true});
  }
  await page.setViewportSize({width:1440,height:900});
  const originalTime=await page.getByLabel('Head 1 delay in milliseconds',{exact:true}).inputValue(),originalFeedback=await page.getByRole('slider',{name:'Intensity',exact:true}).getAttribute('aria-valuenow');
  await page.getByRole('button',{name:'Wander',exact:true}).click();assert.equal(await page.getByLabel('Echo preset',{exact:true}).inputValue(),'Custom');assert.equal(await page.getByRole('slider',{name:'Intensity',exact:true}).getAttribute('aria-valuenow'),originalFeedback);
  await page.getByRole('button',{name:'Return',exact:true}).click();assert.equal(await page.getByLabel('Head 1 delay in milliseconds',{exact:true}).inputValue(),originalTime);assert.equal(await page.getByLabel('Echo preset',{exact:true}).inputValue(),'Warm space');
  pass('Expanded cabinet has no overlap at three desktop sizes; Wander is reversible');

  await page.getByRole('button',{name:'Open library for track 1',exact:true}).click();await page.getByRole('button',{name:/Soft keys/}).click();
  await page.getByRole('button',{name:'Open library for track 2',exact:true}).click();await page.getByRole('button',{name:/Dusty drums/}).click();
  await page.getByRole('button',{name:'Select track 1: Soft keys',exact:true}).click();
  await page.getByRole('button',{name:'Play tape',exact:true}).click();await page.waitForTimeout(650);
  const output=await page.locator('.meter-wrap svg').getAttribute('aria-label');assert(!output.includes(' 0 percent'),`Audio must reach meter: ${output}`);
  pass('Library loads chosen lanes and produces real audio');
  const allocations=await page.evaluate(()=>window.__bufferAllocations);
  await page.getByLabel('Tape speed',{exact:true}).selectOption('.5');await page.waitForTimeout(120);
  await page.getByLabel('Tape speed',{exact:true}).selectOption('1');await page.waitForTimeout(120);
  assert.equal(await page.evaluate(()=>window.__bufferAllocations),allocations,'Changing speed does not reallocate track buffers');
  pass('Live speed changes reuse audio buffers and keep playback running');
  await page.getByRole('button',{name:'Loop track 1',exact:true}).click();
  await page.getByRole('button',{name:'1 beat',exact:true}).click();
  assert.equal(await page.getByLabel('Loop out',{exact:true}).inputValue(),'0.625');
  await page.getByRole('button',{name:'Loop tape',exact:true}).click();
  const nativeLoop=await page.evaluate(()=>window.__sources.slice(-2).map(s=>({loop:s.loop,start:s.loopStart,end:s.loopEnd})));
  assert(nativeLoop[0].loop);assert.equal(nativeLoop[0].end,.625);assert(!nativeLoop[1].loop);
  await page.waitForTimeout(750);assert.equal(await page.getByRole('button',{name:'Loop track 1',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Head 1 tempo sync',exact:true}).click();await page.getByLabel('Tempo',{exact:true}).fill('120');await page.getByLabel('Tempo',{exact:true}).press('Enter');
  await page.getByLabel('Head 1 note division',{exact:true}).selectOption('1/8 D');assert.equal(await page.getByLabel('Head 1 delay in milliseconds',{exact:true}).inputValue(),'375');
  await page.getByLabel('Head 1 delay in milliseconds',{exact:true}).fill('680');await page.getByLabel('Head 1 delay in milliseconds',{exact:true}).press('Enter');assert.equal(await page.getByRole('button',{name:'Head 1 free time',exact:true}).getAttribute('aria-pressed'),'true');
  const swell=page.getByRole('button',{name:'Feedback swell',exact:true});await swell.focus();await page.keyboard.down('Space');assert.equal(await swell.getAttribute('aria-pressed'),'true');await page.keyboard.up('Space');assert.equal(await swell.getAttribute('aria-pressed'),'false');
  const brake=page.getByRole('button',{name:'Tape brake',exact:true});await brake.focus();await page.keyboard.down('Enter');await page.waitForTimeout(150);assert.equal(await brake.getAttribute('aria-pressed'),'true');await page.keyboard.up('Enter');assert.equal(await brake.getAttribute('aria-pressed'),'false');
  await page.getByRole('button',{name:'Echo hold',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Echo hold',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Clear echo',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Echo hold',exact:true}).getAttribute('aria-pressed'),'false');
  const send=page.getByRole('slider',{name:'Selected track echo send',exact:true});await send.fill('0.2');
  const throwButton=page.getByRole('button',{name:'Dub throw',exact:true});await throwButton.focus();await page.keyboard.down('Space');assert.equal(await throwButton.getAttribute('aria-pressed'),'true');await page.keyboard.up('Space');assert.equal(await send.inputValue(),'0.2');
  await page.getByLabel('Selected track playback mode',{exact:true}).selectOption('tape');await page.getByRole('button',{name:'Loop tape',exact:true}).click();await send.fill('1');
  pass('Own track loop uses native A–B timing; tempo sync, numeric delay, brake, swell, hold and dub throw work');
  await page.getByRole('button',{name:'Record master',exact:true}).click();await page.waitForTimeout(500);
  const heldHead2=await page.getByLabel('Head 2 delay in milliseconds',{exact:true}).inputValue();
  await page.getByLabel('Head 3 delay in milliseconds',{exact:true}).fill('1234');await page.getByLabel('Head 3 delay in milliseconds',{exact:true}).press('Enter');
  assert.equal(await page.getByLabel('Head 2 delay in milliseconds',{exact:true}).inputValue(),heldHead2);
  await page.getByRole('button',{name:'Head 2 tempo sync',exact:true}).click();await page.getByLabel('Head 2 note division',{exact:true}).selectOption('1/4 D');assert.equal(await page.getByLabel('Head 2 delay in milliseconds',{exact:true}).inputValue(),'750');
  assert.equal(await page.getByLabel('Head 3 delay in milliseconds',{exact:true}).inputValue(),'1234');
  await page.locator('[data-track="3"]').evaluate((lane,bytes)=>{const dataTransfer=new DataTransfer();dataTransfer.items.add(new File([new Uint8Array(bytes)],'Lane drop.wav',{type:'audio/wav'}));lane.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer}));},Array.from(wav()));
  await page.getByRole('button',{name:'Select track 3: Lane drop',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Select track 1: Soft keys',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Delete track 3 audio',exact:true}).click();await page.getByRole('button',{name:'Select track 3: Empty tape',exact:true}).waitFor();
  await page.getByRole('slider',{name:'Dissolve',exact:true}).focus();await page.keyboard.press('End');
  await page.getByRole('button',{name:'Hold moment',exact:true}).click();await page.waitForTimeout(250);assert.equal(await page.getByRole('button',{name:'Hold moment',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Record cloud motion',exact:true}).click();await page.getByRole('slider',{name:'Scatter',exact:true}).focus();await page.keyboard.press('End');await page.waitForTimeout(200);await page.getByRole('button',{name:'Record cloud motion',exact:true}).click();await page.waitForTimeout(200);assert.equal(await page.getByRole('button',{name:'Loop cloud motion',exact:true}).getAttribute('aria-pressed'),'true');
  // A stalled interface must not interrupt the worklet-to-worker recording path.
  await page.evaluate(()=>{const until=performance.now()+300;while(performance.now()<until){Math.sqrt(Math.random());}});
  await page.getByRole('button',{name:'Loop cloud motion',exact:true}).click();await page.getByRole('button',{name:'Hold moment',exact:true}).click();await page.getByRole('slider',{name:'Dissolve',exact:true}).focus();await page.keyboard.press('Home');
  pass('Independent head timing, lane-accurate drop without selecting it, delete, held cloud and audio-clock motion during master recording');

  await page.getByLabel('Echo preset',{exact:true}).selectOption('Dub satellite');
  await page.getByRole('slider',{name:'Head 1 time',exact:true}).focus();await page.keyboard.press('ArrowUp');
  assert.equal(await page.getByLabel('Echo preset',{exact:true}).inputValue(),'Custom');
  await page.waitForTimeout(700);await page.getByRole('button',{name:'Pause playback',exact:true}).click();await page.waitForTimeout(700);
  await page.getByRole('button',{name:'Stop & save take',exact:false}).click();
  await page.getByRole('button',{name:'Export latest take as WAV',exact:true}).waitFor();
  const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export latest take as WAV',exact:true}).click();const exported=await downloadEvent;await exported.saveAs('test-results/master.wav');
  const bytes=await readFile('test-results/master.wav');assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.toString('ascii',8,12),'WAVE');assert.equal(bytes.readUInt16LE(22),2);assert.equal(bytes.readUInt16LE(34),16);assert.equal(bytes.readUInt32LE(40),bytes.length-44);
  let sum=0,max=0;for(let i=44;i<bytes.length;i+=2){const v=bytes.readInt16LE(i)/32768;sum+=v*v;max=Math.max(max,Math.abs(v));}const rms=Math.sqrt(sum/((bytes.length-44)/2));assert(rms>.005,`Recorded audio is not silent: ${rms}`);assert(max<.999,'Master does not clip');
  let tailEnergy=0;for(let i=bytes.length-24000;i<bytes.length;i+=2){const v=bytes.readInt16LE(i)/32768;tailEnergy+=v*v;}assert(tailEnergy>.001,'Echo tails continue when source playback pauses');
  pass(`Master WAV contains stereo audio and echo tails (RMS ${rms.toFixed(3)}, peak ${max.toFixed(3)})`);
  await page.getByRole('button',{name:'Stop playback',exact:true}).click();
  await page.getByRole('button',{name:'Select track 3: Empty tape',exact:true}).click();
  await page.getByLabel('Import audio files',{exact:true}).setInputFiles({name:'Test impulse.wav',mimeType:'audio/wav',buffer:wav()});
  await page.getByRole('button',{name:'Select track 3: Test impulse',exact:true}).waitFor();
  await page.getByRole('button',{name:'Reverse',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Reverse',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Undo last track edit',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Reverse',exact:true}).getAttribute('aria-pressed'),'false');
  await page.getByLabel('Tape speed',{exact:true}).selectOption('.5');await page.getByRole('button',{name:'Mute track 1',exact:true}).click();await page.getByRole('button',{name:'Solo track 3',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Mute track 1',exact:true}).getAttribute('aria-pressed'),'true');
  pass('WAV import, reverse, undo, tape speed, mute and solo');
  await page.getByLabel('Tape speed',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Solo track 3',exact:true}).click();await page.getByRole('button',{name:'Mute track 1',exact:true}).click();
  await page.getByRole('button',{name:'Record microphone to selected track',exact:true}).click();await page.getByRole('button',{name:'Stop microphone recording',exact:true}).waitFor();await page.waitForTimeout(550);await page.getByRole('button',{name:'Stop microphone recording',exact:true}).click();await page.getByRole('button',{name:'Select track 3: Microphone take',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Monitor microphone',exact:true}).getAttribute('aria-pressed'),'false');
  pass('Microphone capture saves to selected track, monitoring defaults off');
  await page.getByRole('button',{name:'Overdub',exact:true}).click();await page.getByRole('button',{name:'Record microphone to selected track',exact:true}).click();await page.getByRole('button',{name:'Stop microphone recording',exact:true}).waitFor();await page.waitForTimeout(400);await page.getByRole('button',{name:'Stop microphone recording',exact:true}).click();await page.getByRole('button',{name:'Select track 3: Microphone take + overdub',exact:true}).waitFor();
  pass('Microphone overdubbing preserves and layers existing audio');
  await page.getByRole('button',{name:'Select track 4: Empty tape',exact:true}).click();await page.getByRole('button',{name:'Sound library',exact:true}).click();await page.getByRole('button',{name:/Glass bells/}).click();await page.getByRole('button',{name:'Select track 4: Glass bells',exact:true}).waitFor();
  await page.getByRole('button',{name:'Open recorded takes',exact:true}).click();await page.getByRole('button',{name:'To track 4',exact:true}).click();await page.getByRole('button',{name:'Select track 4: Take 01 bounce',exact:true}).waitFor();
  pass('Sound library and resampling master take to tape');
  await page.getByRole('button',{name:'Undo last track edit',exact:true}).click();
  await page.getByRole('button',{name:'Loop track 4',exact:true}).click();await page.getByRole('button',{name:'2 beats',exact:true}).click();await page.getByRole('slider',{name:'Selected track echo send',exact:true}).fill('0.3');await page.getByRole('slider',{name:'Selected track pan',exact:true}).fill('-0.4');await page.getByLabel('Head 3 delay in milliseconds',{exact:true}).fill('1321');await page.getByLabel('Head 3 delay in milliseconds',{exact:true}).press('Enter');await page.getByRole('slider',{name:'Back to tape',exact:true}).focus();await page.keyboard.press('ArrowUp');await page.getByLabel('Session name',{exact:true}).fill('A saved experiment');await page.waitForTimeout(1000);await page.reload();await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal(await page.getByLabel('Session name',{exact:true}).inputValue(),'A saved experiment');await page.getByRole('button',{name:'Select track 3: Microphone take + overdub',exact:true}).waitFor();await page.getByRole('button',{name:'Select track 4: Glass bells',exact:true}).waitFor();await page.getByRole('button',{name:'Export latest take as WAV',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Selected track playback mode',{exact:true}).inputValue(),'loop');assert.equal(await page.getByLabel('Loop out',{exact:true}).inputValue(),'1');assert.equal(await page.getByRole('slider',{name:'Selected track echo send',exact:true}).inputValue(),'0.3');assert.equal(await page.getByRole('slider',{name:'Selected track pan',exact:true}).inputValue(),'-0.4');pass('Session, independent loop, pan/send, audio and master take survive reload');
  assert.equal(await page.getByLabel('Head 3 delay in milliseconds',{exact:true}).inputValue(),'1321');assert.equal(await page.getByRole('slider',{name:'Back to tape',exact:true}).getAttribute('aria-valuenow'),'0.007');
  const stored=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('magnetic-studio');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const tx=db.transaction(['session','clips']);const row=await new Promise(resolve=>{const req=tx.objectStore('session').get('current');req.onsuccess=()=>resolve(req.result);});return {schema:row.schema,embedded:!!row.tracks[0].clip,refs:row.tracks.every(t=>typeof t.clipId==='string'),takes:row.takeIds.length};});
  assert.equal(stored.schema,2);assert.equal(stored.embedded,false);assert(stored.refs);assert.equal(stored.takes,1);
  pass('Session controls are saved separately from sample audio');
  await page.getByLabel('Import audio files',{exact:true}).setInputFiles({name:'bad.wav',mimeType:'audio/wav',buffer:Buffer.from('not audio')});await page.getByRole('status').filter({hasText:'This audio format could not be read'}).waitFor();
  pass('Invalid import reports a useful error without replacing audio');
  await page.getByRole('button',{name:'Dismiss message',exact:true}).click();
  for(const width of [390,320,768]){await page.setViewportSize({width,height:844});await page.waitForTimeout(80);const sizes=await page.evaluate(()=>({w:innerWidth,body:document.documentElement.scrollWidth}));assert(sizes.body<=sizes.w,`No horizontal overflow at ${width}: ${JSON.stringify(sizes)}`);await page.screenshot({path:`test-results/mobile-${width}.png`,fullPage:true});}
  await page.setViewportSize({width:390,height:844});await page.getByRole('slider',{name:'Intensity',exact:true}).focus();await page.keyboard.press('Home');assert.equal(await page.getByRole('slider',{name:'Intensity',exact:true}).getAttribute('aria-valuenow'),'0');
  pass('Responsive 320/390/768 layouts and keyboard knob control');
  await page.getByRole('button',{name:'Field guide',exact:true}).click();await page.getByText('A small field guide',{exact:true}).waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
  await page.waitForFunction(()=>navigator.serviceWorker.controller!==null,undefined,{timeout:15000});await context.setOffline(true);await page.reload();await page.getByText('Saved on this device',{exact:true}).waitFor();await page.getByRole('button',{name:'Play tape from quick controls',exact:true}).click();await page.waitForTimeout(500);assert(!(await page.locator('.meter-wrap svg').getAttribute('aria-label')).includes(' 0 percent'));await page.getByRole('button',{name:'Pause tape from quick controls',exact:true}).click();
  pass('Installed assets and audio processor work after an offline reload');
  const legacyContext=await browser.newContext();const legacy=await legacyContext.newPage();
  await legacy.route('**/__migration',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><title>Migration fixture</title>'}));
  await legacy.goto(base+'/__migration');
  await legacy.evaluate(async wavBytes=>{const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('magnetic-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('session');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const samples=new Float32Array(24000).fill(.125);const tracks=Array.from({length:4},(_,i)=>({clip:i===0?{name:'Existing sample',channels:[samples,samples],sampleRate:24000}:null,volume:.8,muted:false,solo:false,reversed:false}));const tx=db.transaction('session','readwrite');tx.objectStore('session').put({tracks,params:{},heads:[true,false,true],takes:[{id:'legacy-take',name:'Original master',duration:3,blob:new Blob([new Uint8Array(wavBytes)],{type:'audio/wav'})}],name:'Existing session',speed:1,loop:true,enabled:true,selected:0,preset:'Warm space'},'current');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();},Array.from(wav()));
  await legacy.goto(base);await legacy.getByText('Saved on this device',{exact:true}).waitFor();
  assert.equal(await legacy.getByLabel('Session name',{exact:true}).inputValue(),'Existing session');
  await legacy.getByRole('button',{name:'Select track 1: Existing sample',exact:true}).waitFor();
  await legacy.getByRole('slider',{name:'Intensity',exact:true}).focus();await legacy.keyboard.press('ArrowUp');await legacy.getByText('Saved on this device',{exact:true}).waitFor();
  await legacy.reload();await legacy.getByText('Saved on this device',{exact:true}).waitFor();await legacy.getByRole('button',{name:'Select track 1: Existing sample',exact:true}).waitFor();
  const migrationDownload=legacy.waitForEvent('download');await legacy.getByRole('button',{name:'Export latest take as WAV',exact:true}).click();const migrated=await migrationDownload;await migrated.saveAs('test-results/migrated.wav');assert.deepEqual(await readFile('test-results/migrated.wav'),wav());
  await legacyContext.close();pass('Existing version-one sessions migrate without losing sample audio or recorded WAV bytes');
  await context.setOffline(false);await page.setViewportSize({width:1440,height:900});await page.screenshot({path:'test-results/desktop-verified.png',fullPage:true});
  assert.deepEqual(errors,[],'No browser errors');pass('No browser errors');
  await writeFile('test-results/results.json',JSON.stringify({checks,audio:{rms,peak:max,sampleRate:bytes.readUInt32LE(24),bytes:bytes.length}},null,2));
}catch(error){await page.screenshot({path:'test-results/failure.png',fullPage:true}).catch(()=>{});await writeFile('test-results/failure.html',await page.content().catch(()=>''));console.error('Browser errors:',errors);console.error('Offline state:',await page.evaluate(async()=>({text:document.body.innerText.slice(0,700),controller:navigator.serviceWorker.controller?.scriptURL,caches:await caches.keys(),registrations:(await navigator.serviceWorker.getRegistrations()).map(r=>({active:r.active?.state,waiting:r.waiting?.state,installing:r.installing?.state}))})).catch(()=>null));throw error;}finally{await browser.close();}
