import {chromium} from 'playwright';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://localhost:4173';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--autoplay-policy=no-user-gesture-required']});
const context=await browser.newContext({viewport:{width:1440,height:1120},acceptDownloads:true,permissions:['microphone'],reducedMotion:'reduce'});
const page=await context.newPage();const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const checks=[];
const pass=name=>{checks.push(name);process.stdout.write(`PASS ${name}\n`);};
function wav(){const sr=24000,frames=sr*3,b=Buffer.alloc(44+frames*2);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(sr,24);b.writeUInt32LE(sr*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(frames*2,40);for(let i=0;i<frames;i++){const t=i/sr;const s=t<.15?Math.sin(t*Math.PI*440*2)*Math.exp(-t*20)*.5:0;b.writeInt16LE(Math.round(s*32767),44+i*2);}return b;}
try{
  await page.goto(base);await page.getByText('Saved on this device',{exact:true}).waitFor();
  assert.equal(await page.getByRole('slider').count(),13);
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  pass('Initial desktop studio and 13 accessible controls');
  await page.getByRole('button',{name:'Play tape',exact:true}).click();await page.waitForTimeout(650);
  const output=await page.locator('.meter-wrap svg').getAttribute('aria-label');assert(!output.includes(' 0 percent'),`Audio must reach meter: ${output}`);
  pass('Starter loops produce real audio');
  await page.getByRole('button',{name:'Record master',exact:true}).click();await page.waitForTimeout(500);
  await page.getByLabel('Echo preset',{exact:true}).selectOption('Dub satellite');
  await page.getByRole('slider',{name:'Repeat rate',exact:true}).focus();await page.keyboard.press('ArrowUp');
  assert.equal(await page.getByLabel('Echo preset',{exact:true}).inputValue(),'Custom');
  await page.waitForTimeout(700);await page.getByRole('button',{name:'Pause playback',exact:true}).click();await page.waitForTimeout(700);
  await page.getByRole('button',{name:'Stop & save take',exact:false}).click();
  await page.getByRole('button',{name:'Export latest take as WAV',exact:true}).waitFor();
  const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export latest take as WAV',exact:true}).click();const exported=await downloadEvent;await exported.saveAs('test-results/master.wav');
  const bytes=await readFile('test-results/master.wav');assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.toString('ascii',8,12),'WAVE');assert.equal(bytes.readUInt16LE(22),2);assert.equal(bytes.readUInt16LE(34),16);assert.equal(bytes.readUInt32LE(40),bytes.length-44);
  let sum=0,max=0;for(let i=44;i<bytes.length;i+=2){const v=bytes.readInt16LE(i)/32768;sum+=v*v;max=Math.max(max,Math.abs(v));}const rms=Math.sqrt(sum/((bytes.length-44)/2));assert(rms>.005,`Recorded audio is not silent: ${rms}`);assert(max<.999,'Master does not clip');
  let tailEnergy=0;for(let i=bytes.length-24000;i<bytes.length;i+=2){const v=bytes.readInt16LE(i)/32768;tailEnergy+=v*v;}assert(tailEnergy>.001,'Echo tails continue when source playback pauses');
  pass(`Master WAV contains stereo audio and echo tails (RMS ${rms.toFixed(3)}, peak ${max.toFixed(3)})`);
  await page.getByRole('button',{name:'Stop playback',exact:true}).click();
  await page.getByRole('button',{name:'Select track 3: Empty tape',exact:true}).click();
  await page.getByLabel('Import audio files',{exact:true}).setInputFiles({name:'Test impulse.wav',mimeType:'audio/wav',buffer:wav()});
  await page.getByRole('button',{name:'Select track 3: Test impulse',exact:true}).waitFor();
  await page.getByRole('button',{name:'Reverse',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Reverse',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Undo last track edit',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Reverse',exact:true}).getAttribute('aria-pressed'),'false');
  await page.getByLabel('Tape speed',{exact:true}).selectOption('.5');await page.getByRole('button',{name:'Mute track 1',exact:true}).click();await page.getByRole('button',{name:'Solo track 3',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Mute track 1',exact:true}).getAttribute('aria-pressed'),'true');
  pass('WAV import, reverse, undo, tape speed, mute and solo');
  await page.getByLabel('Tape speed',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Solo track 3',exact:true}).click();await page.getByRole('button',{name:'Mute track 1',exact:true}).click();
  await page.getByRole('button',{name:'Record microphone to selected track',exact:true}).click();await page.getByRole('button',{name:'Stop microphone recording',exact:true}).waitFor();await page.waitForTimeout(550);await page.getByRole('button',{name:'Stop microphone recording',exact:true}).click();await page.getByRole('button',{name:'Select track 3: Microphone take',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Monitor microphone',exact:true}).getAttribute('aria-pressed'),'false');
  pass('Microphone capture saves to selected track, monitoring defaults off');
  await page.getByRole('button',{name:'Overdub',exact:true}).click();await page.getByRole('button',{name:'Record microphone to selected track',exact:true}).click();await page.getByRole('button',{name:'Stop microphone recording',exact:true}).waitFor();await page.waitForTimeout(400);await page.getByRole('button',{name:'Stop microphone recording',exact:true}).click();await page.getByRole('button',{name:'Select track 3: Microphone take + overdub',exact:true}).waitFor();
  pass('Microphone overdubbing preserves and layers existing audio');
  await page.getByRole('button',{name:'Select track 4: Empty tape',exact:true}).click();await page.getByRole('button',{name:'Sound library',exact:true}).click();await page.getByRole('button',{name:/Glass bells/}).click();await page.getByRole('button',{name:'Select track 4: Glass bells',exact:true}).waitFor();
  await page.getByRole('button',{name:'Open recorded takes',exact:true}).click();await page.getByRole('button',{name:'To track 4',exact:true}).click();await page.getByRole('button',{name:'Select track 4: Take 01 bounce',exact:true}).waitFor();
  pass('Sound library and resampling master take to tape');
  await page.getByRole('button',{name:'Undo last track edit',exact:true}).click();
  await page.getByLabel('Session name',{exact:true}).fill('A saved experiment');await page.waitForTimeout(1000);await page.reload();await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal(await page.getByLabel('Session name',{exact:true}).inputValue(),'A saved experiment');await page.getByRole('button',{name:'Select track 3: Microphone take + overdub',exact:true}).waitFor();await page.getByRole('button',{name:'Select track 4: Glass bells',exact:true}).waitFor();await page.getByRole('button',{name:'Export latest take as WAV',exact:true}).waitFor();
  pass('Session, audio and master take survive reload');
  await page.getByLabel('Import audio files',{exact:true}).setInputFiles({name:'bad.wav',mimeType:'audio/wav',buffer:Buffer.from('not audio')});await page.getByRole('status').filter({hasText:'This audio format could not be read'}).waitFor();
  pass('Invalid import reports a useful error without replacing audio');
  await page.getByRole('button',{name:'Dismiss message',exact:true}).click();
  for(const width of [390,320,768]){await page.setViewportSize({width,height:844});await page.waitForTimeout(80);const sizes=await page.evaluate(()=>({w:innerWidth,body:document.documentElement.scrollWidth}));assert(sizes.body<=sizes.w,`No horizontal overflow at ${width}: ${JSON.stringify(sizes)}`);await page.screenshot({path:`test-results/mobile-${width}.png`,fullPage:true});}
  await page.setViewportSize({width:390,height:844});await page.getByRole('slider',{name:'Intensity',exact:true}).focus();await page.keyboard.press('Home');assert.equal(await page.getByRole('slider',{name:'Intensity',exact:true}).getAttribute('aria-valuenow'),'0');
  pass('Responsive 320/390/768 layouts and keyboard knob control');
  await page.getByRole('button',{name:'Field guide',exact:true}).click();await page.getByText('A small field guide',{exact:true}).waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
  await page.waitForFunction(()=>navigator.serviceWorker.controller!==null,undefined,{timeout:15000});await context.setOffline(true);await page.reload();await page.getByText('Saved on this device',{exact:true}).waitFor();await page.getByRole('button',{name:'Play tape from quick controls',exact:true}).click();await page.waitForTimeout(500);assert(!(await page.locator('.meter-wrap svg').getAttribute('aria-label')).includes(' 0 percent'));await page.getByRole('button',{name:'Pause tape from quick controls',exact:true}).click();
  pass('Installed assets and audio processor work after an offline reload');
  await context.setOffline(false);await page.setViewportSize({width:1440,height:1120});await page.screenshot({path:'test-results/desktop-verified.png',fullPage:true});
  assert.deepEqual(errors,[],'No browser errors');pass('No browser errors');
  await writeFile('test-results/results.json',JSON.stringify({checks,audio:{rms,peak:max,sampleRate:bytes.readUInt32LE(24),bytes:bytes.length}},null,2));
}catch(error){await page.screenshot({path:'test-results/failure.png',fullPage:true}).catch(()=>{});await writeFile('test-results/failure.html',await page.content().catch(()=>''));console.error('Browser errors:',errors);console.error('Offline state:',await page.evaluate(async()=>({text:document.body.innerText.slice(0,700),controller:navigator.serviceWorker.controller?.scriptURL,caches:await caches.keys(),registrations:(await navigator.serviceWorker.getRegistrations()).map(r=>({active:r.active?.state,waiting:r.waiting?.state,installing:r.installing?.state}))})).catch(()=>null));throw error;}finally{await browser.close();}
