import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const exported={};
vm.runInNewContext(ts.transpileModule(readFileSync('src/audio.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports:exported,Float32Array,Blob,performance});
const param=()=>({value:1,setValueAtTime(v){this.value=v;},linearRampToValueAtTime(v){this.value=v;},cancelScheduledValues(){},setTargetAtTime(v){this.value=v;}});
let allocations=0;
const ctx={currentTime:0,createBuffer(c,n,sr){allocations++;const channels=Array.from({length:c},()=>new Float32Array(n));return {duration:n/sr,getChannelData:c=>channels[c]};},createGain(){return {gain:param(),connect(){},disconnect(){}};},createBufferSource(){return {playbackRate:param(),connect(){},disconnect(){},start(at,offset){this.at=at;this.offset=offset;},stop(){}};}};
const engine=new exported.TapeEngine();engine.ctx=ctx;engine.init=async()=>{};
engine.tracks[0].mode='loop';engine.tracks[0].loopStart=.2;engine.tracks[0].loopEnd=.9;
engine.tracks[1].mode='loop';engine.tracks[1].loopStart=1;engine.tracks[1].loopEnd=2.1;
engine.loop=false;
await engine.play();
assert.equal(engine.sources[0].node.loopStart,.2);assert.equal(engine.sources[0].node.loopEnd,.9);assert.equal(engine.sources[1].node.loopEnd,2.1);
ctx.currentTime=engine.startedAt+23.7;engine.tick();assert(engine.playing,'Own loops keep transport running beyond longest clip');
assert(Math.abs(engine.trackPosition(0)-(.2+23.7%.7))<1e-7);assert(Math.abs(engine.trackPosition(1)-(1+23.7%1.1))<1e-7);
const before=engine.trackPosition(1);engine.pause();await engine.play();assert(Math.abs(engine.sources[1].node.offset-before)<1e-7,'Pause/resume retains independent phase across global tape boundaries');
const count=allocations;engine.setSpeed(.5);ctx.currentTime+=.04;engine.setSpeed(1);assert.equal(allocations,count,'Speed ramp reuses sample buffers');
engine.brake(true);ctx.currentTime+=.8;assert(Math.abs(engine.motorSpeed-.025)<1e-8);engine.brake(false);assert.equal(engine.speed,1);
engine.pause();engine.seek(0);engine.tracks[0].mode='once';engine.tracks[1].mode='once';await engine.play();assert(!engine.sources[0].node.loop);ctx.currentTime=engine.startedAt+11;engine.tick();assert(!engine.playing,'One shots finish with global loop off');
engine.setLoopBounds(0,.15,.6);assert.equal(engine.tracks[0].mode,'loop');engine.reverse(0);engine.undo();assert(!engine.tracks[0].reversed);assert.equal(engine.tracks[0].loopEnd,.6);engine.undo();assert.equal(engine.tracks[0].mode,'once');
engine.setTempo(120,'1/8 D',true);assert.equal(engine.params.time,.375);engine.setTempo(40,'1/2',true);assert.equal(engine.params.time,1.5);engine.setParam('time',.65);assert(!engine.sync);assert.equal(engine.params.time,.65);
console.log('PASS Independent loop phase, A–B bounds, one shots, speed/brake, undo and tempo conversion');

const looping=new exported.TapeEngine();looping.ctx=ctx;looping.init=async()=>{};looping.tracks[0].mode='loop';looping.tracks[0].loopStart=.2;looping.tracks[0].loopEnd=.9;await looping.play();ctx.currentTime=looping.startedAt+23.7;
const phase=looping.trackPosition(0);looping.setClip(2,exported.createDemo('Sub pulse'));assert(Math.abs(looping.trackPosition(0)-phase)<1e-7,'Loading another track preserves independent loop phase after multiple tape laps');
looping.toggleLoop();assert.equal(looping.sources.length,3,'Disabling whole-tape looping lets ordinary tracks finish their current lap');assert(Math.abs(looping.sources[1].node.offset-3.7)<1e-7);assert(Math.abs(looping.trackPosition(0)-phase)<1e-7);
console.log('PASS Imports and global loop changes preserve independent loops and finish the current tape lap');
