import React, {useCallback, useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowDownToLine, ArrowLeftRight, AudioLines, BookOpen, Check, ChevronDown, Circle, Download, FolderOpen, Headphones, HelpCircle, Library, Maximize2, Mic, MoreHorizontal, Pause, Play, Plus, Radio, Repeat2, RotateCcw, SkipBack, SlidersHorizontal, Square, Trash2, Undo2, Upload, Volume2, X} from 'lucide-react';
import {TapeEngine, createDemo, DEFAULTS, PRESETS, type Clip, type Parameters, type Take} from './audio';
import {restoreSession, saveSession} from './storage';
import './style.css';

const engine = new TapeEngine();
const COLORS=['#ba783a','#5d8172','#638198','#947988'];
const formatTime=(seconds:number,decimals=false)=>{const s=Math.max(0,seconds||0);return `${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}${decimals?'.'+Math.floor(s%1*10):''}`;};
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function TapeLogo({size=31}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 36 36" fill="none" aria-hidden="true"><circle cx="10" cy="13" r="6.5" stroke="currentColor" strokeWidth="2.6"/><circle cx="26" cy="13" r="6.5" stroke="currentColor" strokeWidth="2.6"/><circle cx="10" cy="13" r="1.8" fill="currentColor"/><circle cx="26" cy="13" r="1.8" fill="currentColor"/><path d="M3.5 13v15h29V13" stroke="currentColor" strokeWidth="2.6"/></svg>;}
function Screw({className=''}:{className?:string}){return <i aria-hidden="true" className={`screw ${className}`}/>;}

type KnobProps={label:string;value:number;min:number;max:number;defaultValue:number;display:string;onChange:(n:number)=>void;accent?:boolean;description:string};
function Knob({label,value,min,max,defaultValue,display,onChange,accent,description}:KnobProps){
  const drag=useRef<{y:number;value:number}|null>(null);
  const change=(n:number)=>onChange(Math.max(min,Math.min(max,n)));
  const angle=-135+(value-min)/(max-min)*270;
  return <div className={`knob-control ${accent?'accent':''}`}>
    <span className="knob-label">{label}</span>
    <div className="knob-surround">
      <svg viewBox="0 0 110 100" className="knob-ticks" aria-hidden="true">{Array.from({length:11},(_,i)=>{const a=(i*27-225)*Math.PI/180;return <line key={i} x1={55+45*Math.cos(a)} y1={51+45*Math.sin(a)} x2={55+49*Math.cos(a)} y2={51+49*Math.sin(a)}/>;})}</svg>
      <div className="knob" role="slider" tabIndex={0} aria-label={label} aria-valuemin={min} aria-valuemax={max} aria-valuenow={Number(value.toFixed(3))} aria-valuetext={display} title={`${description} Drag up/down, use arrow keys, or double-click to reset.`}
        onPointerDown={e=>{e.preventDefault();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);drag.current={y:e.clientY,value};}}
        onPointerMove={e=>{if(drag.current)change(drag.current.value+(drag.current.y-e.clientY)*(max-min)/(e.shiftKey?1400:180));}}
        onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}
        onDoubleClick={()=>onChange(defaultValue)}
        onKeyDown={e=>{if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();change(e.key==='Home'?min:e.key==='End'?max:value+(['ArrowUp','ArrowRight'].includes(e.key)?1:-1)*(max-min)/(e.shiftKey?1000:100));}}}>
        <span className="knob-cap" style={{transform:`rotate(${angle}deg)`}}><i/></span>
      </div>
    </div>
    <output>{display}</output>
  </div>;
}
function Reel({x,id}:{x:number;id:string}){
  return <g transform={`translate(${x} 95)`}>
    <circle r="71" fill="#100f0d" stroke="#6e6650" strokeWidth="1"/>
    {Array.from({length:8},(_,i)=><circle key={i} r={45+i*3} fill="none" stroke={i%2?'#493d2c':'#6b5940'} strokeWidth="1.5" opacity=".6"/>)}
    <g className="reel-spin">
      <circle r="61" fill={`url(#${id})`} stroke="#96988f" strokeWidth="1.2"/>
      <circle r="56" fill="none" stroke="#414943" strokeWidth=".6"/>
      {[0,120,240].map(a=><g key={a} transform={`rotate(${a})`}><path d="M-10-19 C-26-27-31-36-20-43 C-5-54 15-51 23-40 C29-28 13-20 7-17Z" fill="#25241d" stroke="#55594e" strokeWidth="1.8"/><path d="M-17-40 Q-2-49 16-41" fill="none" stroke="#a4a698" opacity=".6"/></g>)}
      <circle r="15" fill="#565e53" stroke="#c0c3b2" strokeWidth="1.3"/>
      <circle r="9" fill="url(#spindle)" stroke="#31372e" strokeWidth="2"/>
      <rect x="-2" y="-7" width="4" height="14" rx="1" fill="#383c32"/>
      <circle r="3" fill="#d9d8c3"/>
      {[60,180,300].map(a=><circle key={a} cx={48*Math.cos(a*Math.PI/180)} cy={48*Math.sin(a*Math.PI/180)} r="2" fill="#282f27"/>)}
    </g>
  </g>;
}
function TapeMechanism({running,heads,onHead,speed}:{running:boolean;heads:boolean[];onHead:(i:number)=>void;speed:number}){
  return <div className={`tape-window ${running?'running':''}`} style={{'--reel-duration':`${5/speed}s`} as React.CSSProperties}>
    <div className="window-caption"><span><i className={running?'led on':'led'}/>{running?'TAPE IN MOTION':'TAPE READY'}</span><span>STEREO · ¼ INCH</span></div>
    <svg viewBox="0 0 620 230" className="mechanism" aria-label="Animated tape reels and three selectable playback heads">
      <defs>
        <radialGradient id="reelA" cx="35%" cy="20%"><stop stopColor="#e5e4d5"/><stop offset=".4" stopColor="#b7bdb0"/><stop offset=".75" stopColor="#757f70"/><stop offset="1" stopColor="#abb09e"/></radialGradient>
        <linearGradient id="reelB" x1="0" y1="0" x2=".8" y2="1"><stop stopColor="#9aa28f"/><stop offset=".42" stopColor="#d5d8c6"/><stop offset=".7" stopColor="#89927f"/><stop offset="1" stopColor="#b6bda7"/></linearGradient>
        <radialGradient id="spindle" cx="30%" cy="25%"><stop stopColor="#e5e1ce"/><stop offset=".65" stopColor="#a9ac99"/><stop offset="1" stopColor="#555e4f"/></radialGradient>
        <linearGradient id="head-metal" x1="0" x2="1"><stop stopColor="#4e574b"/><stop offset=".2" stopColor="#a6ad99"/><stop offset=".45" stopColor="#d0d1b9"/><stop offset=".7" stopColor="#9da58e"/><stop offset="1" stopColor="#4d5548"/></linearGradient>
      </defs>
      <g className="deck-lines" stroke="#798570" fill="none" opacity=".16"><path d="M32 20h556v184H32Z"/><path d="M295 30v90h55V30"/><path d="M304 34h37v68h-37Z"/></g>
      <path d="M151 25 H466 A70 70 0 0 1 536 95 L551 174 Q553 193 533 193 H88 Q68 193 70 173 L81 95 A70 70 0 0 1 151 25" stroke="#15150f" strokeWidth="7" fill="none"/>
      <path className="moving-tape" d="M151 25 H466 A70 70 0 0 1 536 95 L551 174 Q553 193 533 193 H88 Q68 193 70 173 L81 95 A70 70 0 0 1 151 25" stroke="#8c7048" strokeWidth="3" fill="none"/>
      <Reel x={157} id="reelA"/><Reel x={463} id="reelB"/>
      <g fill="url(#spindle)" stroke="#161c15" strokeWidth="3"><circle cx="79" cy="180" r="12"/><circle cx="542" cy="180" r="12"/><circle cx="298" cy="183" r="15"/></g>
      <g fill="#252c23"><circle cx="79" cy="180" r="4"/><circle cx="542" cy="180" r="4"/><circle cx="298" cy="183" r="5"/></g>
      <rect x="136" y="173" width="37" height="27" rx="4" fill="url(#head-metal)" stroke="#282e24" strokeWidth="2"/><path d="M151 174v23M158 174v23" stroke="#3d4637"/>
      <text x="154" y="219" textAnchor="middle" className="head-svg-label">ERASE</text>
      <rect x="218" y="171" width="33" height="31" rx="4" fill="url(#head-metal)" stroke="#282e24" strokeWidth="2"/><path d="M231 172v28M237 172v28" stroke="#3d4637"/>
      <text x="234" y="219" textAnchor="middle" className="head-svg-label">REC</text>
      {heads.map((active,i)=><g key={i} role="button" tabIndex={0} aria-label={`Playback head ${i+1}`} aria-pressed={active} className={`tape-head ${active?'active':''}`} onClick={()=>onHead(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onHead(i);}}}>
        <rect x={336+i*57} y="157" width="48" height="72" rx="5" fill="transparent"/>
        <rect x={342+i*57} y="171" width="32" height="31" rx="4" fill="url(#head-metal)" stroke={active?'#c4bc80':'#333c2d'} strokeWidth="2"/>
        <path d={`M${355+i*57} 173v26M${361+i*57} 173v26`} stroke="#3d4637"/>
        <circle cx={358+i*57} cy="161" r="3.5" fill={active?'#e9b667':'#434b36'} className="head-light"/>
        <text x={358+i*57} y="219" textAnchor="middle" className="head-svg-label">{i+1}</text>
      </g>)}
      <text x="310" y="61" textAnchor="middle" className="tape-print">MAGNETIC</text><text x="310" y="76" textAnchor="middle" className="tape-print small">CONTINUOUS LOOP</text>
    </svg>
    <div className="glass-reflection"/>
  </div>;
}
function Meter({level,recording}:{level:number;recording:boolean}){return <div className="meter-wrap"><svg viewBox="0 0 240 122" aria-label={`Output meter ${Math.round(level*100)} percent`}>
  <defs><linearGradient id="meter-paper" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#d7ccb0"/><stop offset=".5" stopColor="#efe4c9"/><stop offset="1" stopColor="#d4c5a5"/></linearGradient></defs>
  <rect x="4" y="4" width="232" height="114" rx="7" fill="url(#meter-paper)"/>
  <path d="M31 72 Q120-13 209 72" fill="none" stroke="#4c4b3d" strokeWidth="1.2"/>
  <path d="M161 41 Q189 48 208 67" fill="none" stroke="#ad4b39" strokeWidth="4"/>
  {[-20,-10,-7,-5,-3,0,3].map((n,i)=>{const a=(-143+i*17)*Math.PI/180;return <g key={n}><line x1={120+99*Math.cos(a)} y1={127+99*Math.sin(a)} x2={120+105*Math.cos(a)} y2={127+105*Math.sin(a)} stroke={n>=0?'#a34331':'#514d3c'} strokeWidth="1.4"/><text x={120+117*Math.cos(a)} y={129+117*Math.sin(a)} textAnchor="middle" fontSize="9" fill={n>=0?'#a34331':'#514d3c'}>{n>0?`+${n}`:n}</text></g>;})}
  <text x="120" y="82" textAnchor="middle" fill="#5b5546" fontSize="18" fontWeight="600" fontFamily="Georgia,serif">VU</text><text x="120" y="99" textAnchor="middle" fill="#70654e" fontSize="8" letterSpacing="2">OUTPUT LEVEL</text>
  <g style={{transform:`rotate(${-49+Math.min(1,Math.sqrt(level)*1.8)*96}deg)`,transformOrigin:'120px 124px',transition:'transform 100ms linear'}}><path d="M120 124L119 28L121 28Z" fill="#9b3d2b"/></g>
  <rect x="4" y="107" width="232" height="11" fill="#c9b991" opacity=".8"/>
  </svg><div className="meter-under"><span className={recording?'rec-label':'muted-label'}><i className={`led ${recording?'red on':''}`}/>{recording?'RECORDING':'MASTER OUTPUT'}</span><span>0 dB</span></div></div>;}
function Waveform({clip,color,duration,reversed,position,onSeek}:{clip:Clip|null;color:string;duration:number;reversed:boolean;position:number;onSeek:(s:number)=>void}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas)return;const draw=()=>{const bounds=canvas.getBoundingClientRect();const dpr=window.devicePixelRatio||1;canvas.width=bounds.width*dpr;canvas.height=bounds.height*dpr;const ctx=canvas.getContext('2d')!;ctx.scale(dpr,dpr);ctx.clearRect(0,0,bounds.width,bounds.height);if(!clip)return;const samples=clip.channels[0],w=bounds.width*(samples.length/clip.sampleRate)/duration;const bars=Math.floor(w/3);ctx.fillStyle=color;for(let i=0;i<bars;i++){let peak=0;const start=Math.floor(i/bars*samples.length),end=Math.floor((i+1)/bars*samples.length);for(let j=start;j<end;j+=Math.max(1,Math.floor((end-start)/12))){const idx=reversed?samples.length-1-j:j;peak=Math.max(peak,Math.abs(samples[idx]));}const h=Math.max(1,Math.min(bounds.height-8,peak*(bounds.height-8)*2.7));ctx.fillRect(i*3,(bounds.height-h)/2,1.5,h);}};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect();},[clip,color,duration,reversed]);
  return <div className={`waveform ${clip?'has-clip':''}`} style={{'--track-color':color} as React.CSSProperties} onPointerDown={e=>{if(clip){const r=e.currentTarget.getBoundingClientRect();onSeek((e.clientX-r.left)/r.width*duration);}}}>
    <canvas ref={ref} aria-hidden="true"/>{clip&&<div className="clip-tint" style={{width:`${clip.channels[0].length/clip.sampleRate/duration*100}%`}}/>}
    {clip&&<div className="playhead" style={{left:`${Math.min(100,position/duration*100)}%`}}/>}
  </div>;
}

function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current!;dialog.showModal();return()=>dialog.close();},[]);
  return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}>
    <div className="modal-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}
  </dialog>;
}

function App(){
  const [,render]=useState(0),[ready,setReady]=useState(false),[sessionName,setSessionName]=useState('Sunday experiments'),[saveStatus,setSaveStatus]=useState('Opening session'),[preset,setPreset]=useState('Warm space');
  const [position,setPosition]=useState(0),[level,setLevel]=useState(0),[clock,setClock]=useState(0),[notice,setNotice]=useState(''),[modal,setModal]=useState<'library'|'help'|'takes'|null>(null),[busy,setBusy]=useState(false),[dragging,setDragging]=useState(false),[installPrompt,setInstallPrompt]=useState<any>(null),[online,setOnline]=useState(navigator.onLine);
  const fileRef=useRef<HTMLInputElement>(null),nameRef=useRef(sessionName),presetRef=useRef(preset),saveTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),noticeTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const announce=useCallback((text:string)=>{setNotice(text);clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),5200);},[]);
  const persist=useCallback(()=>{clearTimeout(saveTimer.current);setSaveStatus('Saving…');saveTimer.current=setTimeout(()=>{void saveSession({tracks:engine.tracks,params:engine.params,heads:engine.heads,takes:engine.takes,name:nameRef.current,speed:engine.speed,loop:engine.loop,enabled:engine.enabled,selected:engine.selected,preset:presetRef.current}).then(()=>setSaveStatus('Saved on this device')).catch(()=>{setSaveStatus('Storage full · export your takes');announce('Your browser could not save this session. Export your recordings before closing.');});},650);},[announce]);
  const act=useCallback(async(fn:()=>Promise<unknown>)=>{try{await fn();}catch(e){announce(e instanceof Error?e.message:'Something went wrong. Please try again.');}},[announce]);
  useEffect(()=>{engine.onNotice=announce;let cancelled=false;void restoreSession().then(s=>{if(cancelled)return;if(s&&s.tracks?.length===4){engine.tracks=s.tracks;engine.params={...DEFAULTS,...s.params};engine.heads=s.heads;engine.takes=s.takes||[];engine.speed=s.speed||1;engine.loop=s.loop??true;engine.enabled=s.enabled??true;engine.selected=s.selected||0;nameRef.current=s.name;setSessionName(s.name);presetRef.current=s.preset||'Custom';setPreset(presetRef.current);}setSaveStatus('Saved on this device');}).catch(()=>{setSaveStatus('Session saving unavailable');announce('Device storage is unavailable. Export your takes before closing.');}).finally(()=>{if(!cancelled){setReady(true);engine.onChange=()=>{render(n=>n+1);persist();};}});return()=>{cancelled=true;engine.onChange=()=>{};};},[announce,persist]);
  useEffect(()=>{let frame=0,last=0;const samples=new Float32Array(256);const tick=(t:number)=>{if(t-last>50){engine.tick();setPosition(engine.currentPosition);if(engine.ctx){setClock(engine.ctx.currentTime);if(engine.analyser){engine.analyser.getFloatTimeDomainData(samples);let rms=0;for(const v of samples)rms+=v*v;setLevel(Math.sqrt(rms/samples.length));}}last=t;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(modal||!ready||el.matches('input,select,textarea,button,[role="slider"],[role="button"]')||e.metaKey||e.ctrlKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();if(engine.playing)engine.pause();else void act(()=>engine.play());}if(e.key.toLowerCase()==='r')void act(()=>engine.recording?engine.stopMaster():engine.startMaster());if(e.key.toLowerCase()==='l')engine.toggleLoop();if(e.key.toLowerCase()==='b'){engine.enabled=!engine.enabled;engine.updateParams();engine.onChange();}if(e.key==='Escape')engine.panic();if(!engine.micRecording&&!engine.micArming&&'1234'.includes(e.key)&&e.key.length===1){engine.selected=Number(e.key)-1;engine.onChange();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[act,modal,ready]);
  useEffect(()=>{const beforeInstall=(e:Event)=>{e.preventDefault();setInstallPrompt(e);};const network=()=>setOnline(navigator.onLine);const unload=(e:BeforeUnloadEvent)=>{if(engine.recording||engine.micRecording){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeinstallprompt',beforeInstall);window.addEventListener('online',network);window.addEventListener('offline',network);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('beforeinstallprompt',beforeInstall);window.removeEventListener('online',network);window.removeEventListener('offline',network);window.removeEventListener('beforeunload',unload);};},[]);
  const toggleHead=(i:number)=>{if(engine.heads[i]&&engine.heads.filter(Boolean).length===1){announce('Keep one playback head active, or switch the echo off.');return;}engine.heads=engine.heads.map((v,j)=>j===i?!v:v);presetRef.current='Custom';setPreset('Custom');engine.updateParams();engine.onChange();};
  const setParam=(key:keyof Parameters,n:number)=>{presetRef.current='Custom';setPreset('Custom');engine.setParam(key,n);};
  const loadPreset=(name:string)=>{const p=PRESETS[name];if(!p)return;engine.params={...p.params,volume:engine.params.volume};engine.heads=[...p.heads];engine.updateParams();presetRef.current=name;setPreset(name);engine.onChange();};
  const loadFiles=async(files:FileList|File[])=>{if(engine.micRecording||engine.micArming){announce('Finish the microphone recording before importing.');return;}setBusy(true);try{const list=Array.from(files);for(let i=0;i<Math.min(list.length,4-engine.selected);i++)await engine.importFile(list[i],engine.selected+i);if(list.length>4-engine.selected)announce('Loaded the available tracks. Select track 1 to import up to four files.');}catch(e){announce(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);}};
  const track=engine.tracks[engine.selected];
  const knobs:{key:keyof Parameters;label:string;min:number;max:number;display:string;description:string;accent?:boolean}[]=[
    {key:'time',label:'Repeat rate',min:.055,max:.7,display:`${Math.round(engine.params.time*1000)} ms`,description:'Distance in time to the first playback head. Changing it bends the pitch.',accent:true},
    {key:'feedback',label:'Intensity',min:0,max:1.08,display:`${Math.round(engine.params.feedback*100)}%`,description:'Echo fed back onto the tape. Above 100% the echo can sustain itself.',accent:true},
    {key:'mix',label:'Echo volume',min:0,max:1,display:`${Math.round(engine.params.mix*100)}%`,description:'Balance between the original sound and tape echoes.'},
    {key:'reverb',label:'Spring reverb',min:0,max:1,display:`${Math.round(engine.params.reverb*100)}%`,description:'Spring-inspired diffuse reverb.'},
    {key:'wow',label:'Wow & flutter',min:0,max:1,display:`${Math.round(engine.params.wow*100)}%`,description:'Slow and fast motor fluctuations introduce pitch movement.'},
    {key:'age',label:'Tape age',min:0,max:1,display:engine.params.age<.2?'FRESH':engine.params.age>.7?'WORN':'SEASONED',description:'Darkens the repeated signal, like a well-used tape.'},
    {key:'drive',label:'Saturation',min:0,max:1,display:`${Math.round(engine.params.drive*100)}%`,description:'Soft tape saturation adds harmonics to the echo.'},
    {key:'volume',label:'Output',min:0,max:1,display:engine.params.volume===0?'−∞ dB':`${(20*Math.log10(engine.params.volume)).toFixed(1)} dB`,description:'Master output level. Also affects the master recording.'}
  ];
  const exportTake=(take:Take)=>download(take.blob,`${sessionName.replace(/[^a-z0-9 _-]/gi,'').trim()||'Magnetic'} - ${take.name}.wav`);
  return <>
    <header className="app-header"><a className="brand" href="/" aria-label="Magnetic studio"><TapeLogo/><span>magnetic<span className="brand-dot">®</span></span><i/><small>TAPE ECHO STUDIO</small></a><div className="header-actions"><span className="local-badge"><span className="status-dot"/>{online?'ALL SOUND STAYS HERE':'OFFLINE STUDIO'}</span>{installPrompt&&<button className="text-button" onClick={()=>void act(async()=>{await installPrompt.prompt();setInstallPrompt(null);})}><Download size={15}/>Install</button>}<button className="guide-button" aria-label="Field guide" onClick={()=>setModal('help')}><BookOpen size={16}/><span>Field guide</span></button></div></header>
    <main className={dragging?'dragging':''} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false);}} onDrop={e=>{e.preventDefault();setDragging(false);void loadFiles(e.dataTransfer.files);}}>
      <div className="session-row"><div className="session-name"><span className="eyebrow">SESSION 001</span><input aria-label="Session name" value={sessionName} maxLength={48} onChange={e=>{setSessionName(e.target.value);nameRef.current=e.target.value;if(ready)persist();}}/><span className="session-rule"/></div><div className="save-state"><Check size={14}/>{saveStatus}</div></div>
      <section className={`echo-machine ${engine.enabled?'':'bypassed'}`} aria-label="Tape echo machine">
        <Screw className="top-left"/><Screw className="top-right"/><Screw className="bottom-left"/><Screw className="bottom-right"/>
        <div className="machine-top"><div className="machine-name"><h1>MAGNETIC</h1><span>TAPE ECHO</span></div><div className="machine-model"><span>ANALOG SPIRIT. ENDLESS POSSIBILITIES.</span><b>ME–201</b></div></div>
        <div className="machine-display"><TapeMechanism running={engine.playing||engine.micRecording} heads={engine.heads} onHead={toggleHead} speed={engine.speed}/><div className="machine-sidebar"><Meter level={level} recording={engine.recording}/><div className="head-selector"><span>PLAYBACK HEADS</span><div>{engine.heads.map((active,i)=><button key={i} className={active?'active':''} aria-label={`Head ${i+1}`} aria-pressed={active} onClick={()=>toggleHead(i)}><i/>{i+1}</button>)}</div></div><div className="machine-power"><span>ECHO CIRCUIT</span><button className={`power-toggle ${engine.enabled?'on':''}`} role="switch" aria-label="Echo circuit" aria-checked={engine.enabled} onClick={()=>{engine.enabled=!engine.enabled;engine.updateParams();engine.onChange();}}><span/></button><b>{engine.enabled?'ON':'BYPASS'}</b></div></div></div>
        <div className="control-panel"><div className="panel-topline"><span className="panel-section"><SlidersHorizontal size={13}/> SOUND SHAPING</span><div className="preset-select"><span>PRESET</span><select aria-label="Echo preset" value={preset} onChange={e=>loadPreset(e.target.value)}>{!PRESETS[preset]&&<option>Custom</option>}{Object.keys(PRESETS).map(p=><option key={p}>{p}</option>)}</select><ChevronDown size={13}/></div></div>
          <div className="knob-bank">{knobs.map(({key,...k})=><Knob key={key} {...k} value={engine.params[key]} defaultValue={DEFAULTS[key]} onChange={n=>setParam(key,n)}/>)}</div>
          <div className="control-bottom"><span className="knob-hint">DRAG TO TURN <i/> DOUBLE-CLICK TO RESET</span><label className="tone-control">TONE <span>DARK</span><input type="range" aria-label="Echo tone" min="0" max="1" step=".01" value={engine.params.tone} onChange={e=>setParam('tone',Number(e.target.value))}/><span>BRIGHT</span></label><button className="panic-button" onClick={()=>engine.panic()} title="Clear the echo and reset feedback (Escape)"><RotateCcw size={12}/>Clear echo</button></div>
        </div>
      </section>
      <div className="studio-bottom"><section className="tape-recorder" aria-label="Four-track recorder"><div className="section-header"><div><TapeLogo size={20}/><h2>Four-track tape</h2><span className="small-tag">STEREO</span></div><div><button className="icon-button" aria-label="Undo last track edit" title="Undo last track edit" disabled={!engine.hasUndo||engine.micRecording} onClick={()=>engine.undo()}><Undo2 size={16}/></button><button className="text-button" disabled={busy||!ready||engine.micRecording} onClick={()=>setModal('library')}><Library size={15}/>Sound library</button></div></div>
        <div className="tape-transport"><div className="transport-buttons"><button aria-label="Rewind to start" title="Rewind to start" onClick={()=>engine.seek(0)}><SkipBack size={17} fill="currentColor"/></button><button aria-label="Stop playback" title="Stop playback" onClick={()=>engine.stop()}><Square size={15} fill="currentColor"/></button><button className={`play-button ${engine.playing?'playing':''}`} aria-label={engine.playing?'Pause playback':'Play tape'} title="Play / pause (Space)" disabled={!ready} onClick={()=>{if(engine.playing)engine.pause();else void act(()=>engine.play());}}>{engine.playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button className={`mic-record-button ${engine.micRecording?'recording':''}`} aria-label={engine.micRecording?'Stop microphone recording':'Record microphone to selected track'} title={`Record microphone to track ${engine.selected+1}`} disabled={!ready||engine.micArming} onClick={()=>void act(()=>engine.micRecording?engine.stopMic():engine.startMic(engine.selected))}>{engine.micRecording?<Square size={15} fill="currentColor"/>:<Circle size={16} fill="currentColor"/>}</button></div><div className="transport-time"><span>{formatTime(position,true)}</span><small>/ {formatTime(engine.duration)}</small></div><div className="transport-options"><button className={engine.loop?'active':''} aria-label="Loop tape" title="Loop tape (L)" aria-pressed={engine.loop} onClick={()=>engine.toggleLoop()}><Repeat2 size={18}/></button><label title="Tape speed changes playback pitch"><span>SPEED</span><select aria-label="Tape speed" value={engine.speed} disabled={engine.micRecording} onChange={e=>engine.setSpeed(Number(e.target.value))}><option value=".5">½×</option><option value=".75">¾×</option><option value="1">1×</option><option value="1.5">1½×</option><option value="2">2×</option></select></label></div></div>
        <div className="tape-ruler"><span>TRACK</span><div>{Array.from({length:5},(_,i)=><span key={i}>{formatTime(engine.duration*i/4)}</span>)}</div><span>LEVEL</span></div>
        <div className="tracks">{engine.tracks.map((t,i)=><div key={i} className={`track ${engine.selected===i?'selected':''} ${t.muted?'is-muted':''}`} style={{'--track-color':COLORS[i]} as React.CSSProperties} onDragOver={e=>{e.preventDefault();e.stopPropagation();}} onDrop={e=>{e.preventDefault();e.stopPropagation();setDragging(false);if(engine.micRecording||engine.micArming){announce('Finish the microphone recording before importing.');return;}engine.selected=i;engine.onChange();void loadFiles(e.dataTransfer.files);}}>
          <button className="track-name" disabled={engine.micRecording||engine.micArming} onClick={()=>{engine.selected=i;engine.onChange();}} aria-label={`Select track ${i+1}: ${t.clip?.name||'Empty tape'}`} aria-pressed={engine.selected===i}><span className={`track-number ${engine.micRecording&&engine.selected===i?'recording':''}`}>{String(i+1).padStart(2,'0')}</span><span className="clip-name">{engine.micRecording&&engine.selected===i?'Recording…':t.clip?.name||'Empty tape'}<small>{t.clip?(t.reversed?'REVERSED':'STEREO'):'READY TO RECORD'}</small></span></button>
          <div className="track-lane"><Waveform clip={t.clip} color={COLORS[i]} duration={engine.duration} reversed={t.reversed} position={position} onSeek={p=>engine.seek(p)}/>{!t.clip&&!(engine.micRecording&&engine.selected===i)&&<button className="empty-clip" disabled={engine.micRecording} onClick={()=>{engine.selected=i;engine.onChange();fileRef.current?.click();}}><Plus size={13}/>Drop a sound or record</button>}{engine.micRecording&&engine.selected===i&&<div className="recording-wave"><Activity size={18}/> {formatTime(clock-engine.micStarted,true)}</div>}</div>
          <div className="track-controls"><button aria-label={`Mute track ${i+1}`} aria-pressed={t.muted} className={t.muted?'active':''} onClick={()=>{t.muted=!t.muted;engine.updateGains();engine.onChange();}}>M</button><button aria-label={`Solo track ${i+1}`} aria-pressed={t.solo} className={t.solo?'solo active':''} onClick={()=>{t.solo=!t.solo;engine.updateGains();engine.onChange();}}>S</button><input type="range" aria-label={`Track ${i+1} volume`} min="0" max="1" step=".01" value={t.volume} onChange={e=>{t.volume=Number(e.target.value);engine.updateGains();engine.onChange();}}/></div>
        </div>)}</div>
        <div className="track-tools"><div><button className="text-button import-button" disabled={busy||!ready||engine.micRecording} onClick={()=>fileRef.current?.click()}><Upload size={14}/>{busy?'Importing…':'Import audio'}</button><span className="tool-separator"/><button className={`text-button ${track.reversed?'active':''}`} disabled={!track.clip||engine.micRecording} aria-pressed={track.reversed} onClick={()=>engine.reverse(engine.selected)} title="Reverse the selected track"><ArrowLeftRight size={14}/><span>Reverse</span></button><button className="icon-button" disabled={!track.clip||engine.micRecording} onClick={()=>{engine.setClip(engine.selected,null);announce('Track cleared. Undo restores it.');}} aria-label="Clear selected track"><Trash2 size={14}/></button></div><div><button className={`text-button ${engine.overdub?'active':''}`} aria-pressed={engine.overdub} disabled={engine.micRecording} onClick={()=>{engine.overdub=!engine.overdub;engine.onChange();announce(engine.overdub?'Overdub on: new microphone recordings layer onto the selected track.':'Overdub off: new microphone recordings replace the selected track.');}} title="Layer a microphone recording onto the selected track"><Plus size={13}/>Overdub</button><button className={`icon-button ${engine.monitoring?'active':''}`} aria-label="Monitor microphone" aria-pressed={engine.monitoring} title="Hear the microphone through the echo. Use headphones." onClick={()=>{engine.setMonitoring(!engine.monitoring);if(engine.monitoring)announce('Mic monitoring on. Use headphones to avoid speaker feedback.');}}><Headphones size={15}/></button></div></div>
      </section>
      <section className={`master-recorder ${engine.recording?'is-recording':''}`} aria-label="Master recorder"><div className="section-header"><div><Radio size={17}/><h2>Master recorder</h2></div><span className="small-tag">WAV</span></div><div className="master-body"><div className="master-display"><div className="master-status"><span><i className={`led ${engine.recording?'red on':''}`}/>{engine.recording?'CAPTURING OUTPUT':'READY TO CAPTURE'}</span><span>STEREO</span></div><div className="master-time">{formatTime(engine.recording?clock-engine.recordingStarted:0,true)}<span>{engine.ctx?(engine.ctx.sampleRate/1000).toFixed(1):'48'} kHz / 16 BIT</span></div><div className="digital-meter">{Array.from({length:36},(_,i)=><i key={i} className={i<Math.sqrt(level)*75?'lit':''} style={{'--meter-color':i>30?'#d17454':i>25?'#cfad59':'#97ad7b'} as React.CSSProperties}/>)}</div></div><button className={`master-record ${engine.recording?'recording':''}`} aria-label={engine.recording?'Stop & save take':'Record master'} disabled={!ready} onClick={()=>void act(()=>engine.recording?engine.stopMaster():engine.startMaster())}>{engine.recording?<Square size={13} fill="currentColor"/>:<Circle size={13} fill="currentColor"/>}{engine.recording?'Stop & save take':'Record master'}<kbd>R</kbd></button><p className="master-hint">Capture everything you hear.<br/>Every loop, every turn, every happy accident.</p><div className="take-shelf"><div><span>YOUR TAKES</span><button onClick={()=>setModal('takes')} aria-label="Open recorded takes">{String(engine.takes.length).padStart(2,'0')}<ChevronDown size={13}/></button></div>{engine.takes.length?<div className="latest-take"><button className="take-info" onClick={()=>setModal('takes')}><AudioLines size={17}/><span>{engine.takes[0].name}<small>{formatTime(engine.takes[0].duration,true)} · WAV</small></span></button><button className="icon-button" aria-label="Export latest take as WAV" title="Download WAV" onClick={()=>exportTake(engine.takes[0])}><ArrowDownToLine size={17}/></button></div>:<div className="no-takes"><AudioLines size={20}/><span>Your next idea starts here.</span></div>}</div></div></section></div>
      <footer><span><span className="footer-mark">m.</span> MADE FOR GETTING LOST IN SOUND.</span><div><span><kbd>SPACE</kbd> play / pause</span><span><kbd>1</kbd>–<kbd>4</kbd> select track</span><button onClick={()=>setModal('help')} aria-label="Help and keyboard shortcuts"><HelpCircle size={15}/></button></div></footer>
      {dragging&&<div className="drop-overlay"><Upload size={36}/><h2>Put it on tape.</h2><p>Drop audio onto a track, or anywhere to import.</p></div>}
    </main>
    <div className="mobile-dock" aria-label="Quick tape controls"><div><span>TRACK {String(engine.selected+1).padStart(2,'0')}</span><b>{track.clip?.name||'Empty tape'}</b></div><button className="dock-play" aria-label={engine.playing?'Pause tape from quick controls':'Play tape from quick controls'} disabled={!ready} onClick={()=>{if(engine.playing)engine.pause();else void act(()=>engine.play());}}>{engine.playing?<Pause size={16} fill="currentColor"/>:<Play size={16} fill="currentColor"/>}{engine.playing?'Pause':'Play'}</button><button className={`dock-record ${engine.recording?'recording':''}`} aria-label={engine.recording?'Save master from quick controls':'Record master from quick controls'} disabled={!ready} onClick={()=>void act(()=>engine.recording?engine.stopMaster():engine.startMaster())}>{engine.recording?<Square size={12} fill="currentColor"/>:<Circle size={12} fill="currentColor"/>}{engine.recording?'Save':'Rec'}</button><button className="dock-import" aria-label="Import audio from quick controls" disabled={busy||!ready||engine.micRecording} onClick={()=>fileRef.current?.click()}><Upload size={18}/></button></div>
    <input ref={fileRef} className="visually-hidden" type="file" accept="audio/*,.wav,.mp3,.m4a,.aif,.aiff,.ogg,.flac" multiple aria-label="Import audio files" onChange={e=>{if(e.target.files)void loadFiles(e.target.files);e.target.value='';}}/>
    {notice&&<div className="toast" role="status"><AudioLines size={17}/><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {modal==='library'&&<Modal title="Sound library" subtitle={`A few starting points. Load a sound onto track ${engine.selected+1}.`} onClose={()=>setModal(null)}><div className="sample-list">{[{name:'Soft keys',tag:'MELLOW ELECTRIC KEYS',type:'CHORDS',color:COLORS[0]},{name:'Dusty drums',tag:'LOOSE, WARM & UNHURRIED',type:'DRUMS',color:COLORS[1]},{name:'Sub pulse',tag:'A LITTLE LOW-END WEIGHT',type:'BASS',color:COLORS[2]},{name:'Glass bells',tag:'BRIGHT NOTES, LONG SHADOWS',type:'MELODY',color:COLORS[3]}].map(s=><button className="sample-card" key={s.name} onClick={()=>{engine.setClip(engine.selected,createDemo(s.name));setModal(null);announce(`${s.name} loaded on track ${engine.selected+1}. Press play.`);}}><div className="sample-icon" style={{color:s.color}}><AudioLines size={27}/></div><div><b>{s.name}</b><small>{s.tag}</small></div><span>96 BPM<br/>{s.type}</span><Plus size={19}/></button>)}</div><p className="modal-footnote">Original sounds, made for this studio. 4 bars · 10 seconds · C minor.<br/>You can also drag your own audio onto any track.</p></Modal>}
    {modal==='takes'&&<Modal title="Your master takes" subtitle="The complete output, including your live echo movements." onClose={()=>setModal(null)}><div className="takes-list">{engine.takes.length===0?<div className="takes-empty"><Radio size={34}/><h3>Nothing on the reel. Yet.</h3><p>Press Record master, play your tape, and shape the sound. Stop recording to save a WAV take here.</p></div>:engine.takes.map(t=><div className="take-card" key={t.id}><div className="take-title"><AudioLines size={21}/><b>{t.name}</b><small>{formatTime(t.duration,true)} · {(t.blob.size/1024/1024).toFixed(1)} MB</small></div><TakePlayer take={t}/><div className="take-buttons"><button className="text-button" onClick={()=>exportTake(t)}><Download size={15}/>Export WAV</button><button className="text-button" disabled={engine.micRecording} onClick={()=>void act(async()=>{setBusy(true);try{await engine.importFile(new File([t.blob],`${t.name} bounce.wav`,{type:'audio/wav'}),engine.selected);setModal(null);}finally{setBusy(false);}})}><Repeat2 size={15}/>To track {engine.selected+1}</button><button className="icon-button" aria-label={`Delete ${t.name}`} onClick={()=>{engine.takes=engine.takes.filter(x=>x.id!==t.id);engine.onChange();}}><Trash2 size={15}/></button></div></div>)}</div><p className="modal-footnote">Recorded locally. 16-bit stereo WAV at your device’s audio rate.<br/>Each recording stops automatically at 10 minutes.</p></Modal>}
    {modal==='help'&&<Modal title="A small field guide" subtitle="Think of it as a tape machine you can take anywhere." onClose={()=>setModal(null)} wide><div className="guide-grid"><article><span>01 / PUT SOMETHING ON TAPE</span><h3>Start with a sound.</h3><p>Press play to hear the starter loop. Select one of four tracks, import an audio file, or press the red button beside Play to record your microphone. New recordings replace that track; Undo brings it back.</p></article><article><span>02 / FOLLOW THE ECHO</span><h3>A little movement goes a long way.</h3><p>Drag knobs up or down. Repeat rate sets the time to head 1; heads 2 and 3 repeat at two and three times that interval. Intensity feeds echoes back into the tape. Try changing the rate while a note rings out.</p></article><article><span>03 / MAKE IT YOURS</span><h3>Slow it. Flip it. Layer it.</h3><p>Tape speed changes pitch and length together. Reverse flips a selected track. Overdub layers microphone audio at the current tape position. Turn on headphone monitoring to hear your mic through the echo; use headphones.</p></article><article><span>04 / KEEP THE GOOD PART</span><h3>Record the whole performance.</h3><p>Record master captures the complete output, including effect tails. Stop and save when you’re done, then export a stereo WAV. Send a take back to a track to build another layer.</p></article></div><div className="guide-notes"><h3>At home. On the move.</h3><p>Tracks, settings, and takes save in this browser on this device. Audio stays local. Install from your browser menu; on iPhone or iPad, use Share → Add to Home Screen. After the first complete visit, the installed app works offline. Keep the app open while recording.</p><p>Import WAV, MP3, M4A, OGG, FLAC, or other audio your browser supports, up to 60 MB and 3 minutes per sample. Microphone recording requires a secure connection and permission. Master takes stop at 10 minutes.</p></div><div className="shortcuts">{[['Space','Play / pause'],['R','Master record'],['L','Loop'],['B','Echo bypass'],['1–4','Select track'],['Esc','Clear echo']].map(([key,label])=><span key={key}><kbd>{key}</kbd>{label}</span>)}</div><p className="modal-footnote">An original digital instrument inspired by the <a href="https://articles.roland.com/tips-and-tricks-roland-cloud-re-201-space-echo/" target="_blank" rel="noreferrer">Roland RE-201</a> and <a href="https://teenage.engineering/guides/op-1/original/tape-mode" target="_blank" rel="noreferrer">OP-1 tape workflow</a>. Spring-style reverb and tape character are creative approximations. Not affiliated with Roland or teenage engineering.</p></Modal>}
  </>;
}
function TakePlayer({take}:{take:Take}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(take.blob);setUrl(u);return()=>URL.revokeObjectURL(u);},[take.blob]);return <audio controls src={url} preload="none" aria-label={`Preview ${take.name}`}/>;}

createRoot(document.getElementById('root')!).render(<App/>);
if(import.meta.env.PROD&&'serviceWorker' in navigator){window.addEventListener('load',()=>{void navigator.serviceWorker.register('/sw.js').catch(()=>{});});}
